import re
from playwright.sync_api import sync_playwright, expect
def test_crossbrowser(page):
        page.goto("https://demo.pricefx.com/app/?partition=demofx_experis#/login?redirect_url=%2Fqc%2Fquotes")
        assert page.url.startswith("https://demo.pricefx.com")
        page.wait_for_timeout(3000)
        page.locator("[data-test=\"username-input\"]").click()
        page.locator("[data-test=\"username-input\"]").fill("shreyas")
        page.locator("[data-test=\"password-input\"]").click()
        page.locator("[data-test=\"password-input\"]").fill("Shreyas@29409")
        page.locator("[data-test=\"login-loginbutton-button\"]").click()
        page.wait_for_timeout(5000)
        page.locator("[data-test=\"priceshop-newquotename-button\"]").click()
        page.wait_for_timeout(5000)
        page.get_by_role("link", name="Automation_Quote").click()
        page.locator("[data-test=\"targetdate-input\"]").click()
        page.get_by_role("button", name="2026").click()
        page.get_by_text("2025").click()
        page.get_by_text("1").nth(2).click()
        page.locator("[data-test=\"expirydate-input\"]").click()
        page.get_by_text("Today").nth(1).click()
        page.wait_for_timeout(3000)
        page.locator("[data-test=\"customer-select-addon\"]").click()
        page.locator("[data-test=\"quick-filter-Customer-Id-input\"]").get_by_role("textbox", name="Search…").click()
        page.locator("[data-test=\"quick-filter-Customer-Id-input\"]").get_by_role("textbox", name="Search…").fill(
            "CH-0001")
        page.locator("[data-test=\"quick-filter-Customer-Id-input\"]").get_by_role("textbox", name="Search…").press(
            "Enter")
        page.wait_for_timeout(2000)
        page.get_by_role("row").filter(has_text="CH-0001").get_by_label("").first.click()
        page.get_by_text("Select item").click()
        page.locator("[id=\"Detail-:QuoteDiscountPercent\"]").click()
        page.get_by_text("Biggest").click()
        page.locator("[data-test=\"Q-detail-tab--items\"]").click()
        page.locator("[data-test=\"sfdc-import-add-items-button\"]").click()
        page.get_by_role("button", name="Hot Fill Juice 128 oz").click()
        page.get_by_role("row", name="Press SHIFT+SPACE to select").get_by_label("", exact=True).click()
        page.locator("[data-test=\"productdiscountpercent-input\"]").click()
        page.locator("[data-test=\"productdiscountpercent-input\"]").fill("10")
        page.locator("div").filter(has_text=re.compile(r"^QuantityProduct Discount Percent %$")).nth(2).click()
        page.locator("[data-test=\"priceshop-recalculate-button\"]").click()
        page.locator("[data-test='common-submit-button']").first.click()
        modal = page.locator("[data-test='unity-quote-submitconfirmation-modal']")
        modal.wait_for(state="visible")
        modal.get_by_role("textbox", name="Your comment (optional)").fill("Test")
        submit_btn = modal.locator("[data-test='common-submit-button']")
        submit_btn.wait_for(state="visible")
        submit_btn.click()
        page.locator("[data-test='Q-detail-tab--workflow']").wait_for(state="visible")
        page.locator("[data-test='Q-detail-tab--workflow']").click()
        page.get_by_text("Workflow Submitted by shreyas").wait_for(state="visible")
        expect(page.get_by_text("Workflow Submitted by shreyas")).to_be_visible()
        page.locator(".ucButton.ucButton--hasIcon.ucButton--iconOnly.ucButton--iconOnlyColor-green > .ucButton__inner").wait_for(state="visible")
        page.locator(".ucButton.ucButton--hasIcon.ucButton--iconOnly.ucButton--iconOnlyColor-green > .ucButton__inner").click()
        page.get_by_text("Add Approval Reason").wait_for(state="visible")
        page.get_by_role("textbox", name="Reason for your decision").fill("Test")
        page.locator("[data-test='common-approve-button']").wait_for(state="visible")
        page.locator("[data-test='common-approve-button']").click()
        page.get_by_text("Quote has been approved").wait_for(state="visible")
        expect(page.get_by_text("Quote has been approved")).to_be_visible()
        ##browser.close()

CrossBrowser:
pytest Demo/test_crossbrowser.py -s -v --headed --browser firefox --browser chromium 
